---
title: "Case Study 1"
author: "Ben Pitman"
date: "1/10/2020"
output: 
  html_document:
    theme: spacelab
    
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gapminder)
library(car)
library(mosaic)
library(ggplot2)
library(tidyverse)

```


___
# Examples
___

## Unique/ Good

### Height of NBA Players

<https://www.probasketballtroops.com/average-nba-height/>

#### Response

In this graphic it shows the height of NBA players starting at the year 1952 and ending at 2018. The X axis is labeled in 11 years increments. It is found that from 1952 to 1985 the average height increased but around 1985 the heights stay around the same. For the past 30 years the height has stay around the same.



#### Issue

I think what they could have done better is to add grid lines to see better where the heights are on the axis but it's a little hard to see where the heights are.


### Presidential Votes

<https://www.270towin.com/news/2017/01/24/if-electoral-votes-were-weighted-by-state-population-alone-trump-303-clinton-235_442.html>

#### Response

This graphic is of the 2016 Presidential Election showing which political party each state voted for and how many electoral votes where given by each state. It also shows a tally of how many electoral college Trump or Clinton received. It had the title of Population- Weighted Electoral Vote Distribution.


#### Issue
The biggest issue is that it doesn't show the popular vote just the electoral college. This is problem it would make it appear that more people in America voted for Trump when Clinton received more votes.


## Not so good

### State population per electoral voting

<https://commons.wikimedia.org/wiki/File:State_population_per_electoral_vote.png>

#### Response

In this graphic there is a bar graph showing each state and their population per electoral vote. This is used to show that electoral votes in one state have a higher population than in other states. The highest is California and the lowed in Wyoming.

#### Issue
The biggest issue with this graphic is the fact that there is a color element but for no reason. It just changes and there appears to be no reason for it.

### More Height of NBA Players

<https://sports.stackexchange.com/questions/15353/what-is-the-average-height-in-the-nba>

#### Response
In this graphic there is a bar graph of how many NBA players are at the specific height. The heights go from 5 feet 9 inches to 7 feet 3 inches. The Y axis is done in intervals of 5 players with the most being 60. There are also grid lines to show numbers more specifically.

#### Issue

The biggest problem with the graph is it doesn't tell you a year or anything other than how many players are at the height. If I saw it by it's self I would not know what it was showing.
